### ISSUE TITLE
checkra1n Load KPPmodule failed

### ISSUE THREAD

**Issue by adm1n007** [dora2-iOS/CPBypass2#1]
I tried loading KPPmodule and it stopped here. What should I do next?
iphone7 ios13.3.1
![image](https://user-images.githubusercontent.com/2877578/110308181-c8c8e680-803a-11eb-9a40-bd1696d1449d.png)

**Comment by adm1n007** [comment]
I wanna test the offsets just found.
` bootargs_store      = OFFSET(0xFFFFFFF0070EE820);`
`ml_phys_read_data   = OFFSET(0xFFFFFFF007231ABC);`
`ml_phys_write_data  = OFFSET(0xFFFFFFF007231CEC);`
`sysent_stat        = OFFSET(0xFFFFFFF0070D6710);`
`copyinstr          = OFFSET(0xFFFFFFF00722C7E4);`
`_IOLog              = OFFSET(0xFFFFFFF007630CB0);`
`_strcmp             = OFFSET(0xFFFFFFF00720BF00);`
`_payload_base       = OFFSET(0xFFFFFFF0076E3710);`

Maybe the offsets are incorrect. 😅

**Comment by dora2-iOS** [comment]
A10 devices do not have KPP. It's a KTRR device. Currently, there is no support other than A9 devices.

**Comment by adm1n007** [comment]
> A10 devices do not have KPP. It's a KTRR device. Currently, there is no support other than A9 devices.

Aha... My mistake. So silly I am... 😅    
thanks. And please add support for iphone 7 or up.
