### ISSUE TITLE
Did support iOS13 ?

### ISSUE THREAD

**Issue by adm1n007** [dora2-iOS/CPBypass2#4]
I tested on 6s iOS 13.2 with the offsets i found and failed.

`/*---- S8000 17B84 [13.2] ----*/`
`ml_phys_read_data   = OFFSET(0xFFFFFFF0071F0060);`
`ml_phys_write_data  = OFFSET(0xFFFFFFF0071F0290);`
`_sysent_stat        = OFFSET(0xFFFFFFF00709A958);`
`_copyinstr          = OFFSET(0xFFFFFFF0071EAE78);`
`_IOLog              = OFFSET(0xFFFFFFF0075F07E0);`
`_strcmp             = OFFSET(0xFFFFFFF0071CAC00);`
`_payload_base       = OFFSET(0xFFFFFFF0076A36D0);`

**Comment by dora2-iOS** [comment]
There is no need to report that it does not work.  I will add it if it works.
